version: '2.2'
services:
  es01:
    image: elastic-plugin:${STACK_VERSION}
    container_name: es-plugin-01
    environment:
      - node.name=es-plugin-01
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es-plugin-02,es-plugin-03
      - cluster.initial_master_nodes=es-plugin-01,es-plugin-02,es-plugin-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - ${OS_PORT}:9200
    networks:
      - elastic
  es02:
    image: elastic-plugin:${STACK_VERSION}
    container_name: es-plugin-02
    environment:
      - node.name=es-plugin-02
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es-plugin-01,es-plugin-03
      - cluster.initial_master_nodes=es-plugin-01,es-plugin-02,es-plugin-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: elastic-plugin:${STACK_VERSION}
    container_name: es-plugin-03
    environment:
      - node.name=es-plugin-03
      - cluster.name=${CLUSTER_NAME}
      - discovery.seed_hosts=es-plugin-01,es-plugin-02
      - cluster.initial_master_nodes=es-plugin-01,es-plugin-02,es-plugin-03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic
  kib01:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kib-plugin-01
    ports:
      - ${DASHBOARDS_PORT}:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    networks:
      - elastic

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge